// <auto-generated />
using CoffeeHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112220151_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeHub.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A rich and bold espresso made from premium Arabica beans, perfect for strong coffee lovers.",
                            Image = "espresso.png",
                            Name = "Classic Espresso",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Smooth coffee infused with warm hazelnut notes for a nutty and comforting flavor.\",\r\n  },",
                            Image = "hazelnut.png",
                            Name = "Hazelnut Coffee",
                            Price = 7.49m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A balanced coffee blend with subtle vanilla sweetness for a smooth, aromatic cup.",
                            Image = "vanilla.png",
                            Name = "Vanilla Brew",
                            Price = 7.29m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Medium-roasted coffee with buttery caramel undertones and a naturally sweet finish.",
                            Image = "caramel.png",
                            Name = "Caramel Roast",
                            Price = 7.59m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A deep coffee blend combined with chocolate notes for a rich and indulgent taste.",
                            Image = "mocha.png",
                            Name = "Mocha Blend",
                            Price = 7.89m
                        },
                        new
                        {
                            Id = 6,
                            Description = "A bold coffee infused with dark chocolate and fruity raspberry accents for a unique twist.",
                            Image = "chocoRaspberry.png",
                            Name = "Chocolate Raspberry",
                            Price = 8.29m
                        },
                        new
                        {
                            Id = 7,
                            Description = "A refreshing coffee blend with tangy raw mango notes for an unexpected, vibrant flavor.",
                            Image = "mango.png",
                            Name = "Raw Mango",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Light coffee with tropical pineapple hints, delivering a bright and refreshing taste.",
                            Image = "pineapple.png",
                            Name = "Pineapple Delight",
                            Price = 7.79m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Smooth coffee infused with roasted pistachio flavor for a creamy, nut-forward finish.",
                            Image = "pistachio.png",
                            Name = "Royal Pistachio",
                            Price = 8.49m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
