// <auto-generated />
using System;
using CoffeeHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeHub.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127181917_AddPaymentsTable")]
    partial class AddPaymentsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeHub.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A rich and bold espresso made from premium Arabica beans, perfect for strong coffee lovers.",
                            Image = "https://coffeehubimg02.blob.core.windows.net/product-images/ExpressoCoffee.png",
                            Name = "Classic Espresso",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Smooth coffee infused with warm hazelnut notes for a nutty and comforting flavor.",
                            Image = "https://coffeehubimg02.blob.core.windows.net/product-images/HazelnutCoffee.png",
                            Name = "Hazelnut Coffee",
                            Price = 7.49m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A balanced coffee blend with subtle vanilla sweetness for a smooth, aromatic cup.",
                            Image = "https://coffeehubimg02.blob.core.windows.net/product-images/VanilaCoffee.png",
                            Name = "Vanilla Brew",
                            Price = 7.29m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Medium-roasted coffee with buttery caramel undertones and a naturally sweet finish.",
                            Image = "https://coffeehubimg02.blob.core.windows.net/product-images/CaramelCoffee.png",
                            Name = "Caramel Roast",
                            Price = 7.59m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A deep coffee blend combined with chocolate notes for a rich and indulgent taste.",
                            Image = "https://coffeehubimg02.blob.core.windows.net/product-images/MochaCoffee.png",
                            Name = "Mocha Blend",
                            Price = 7.89m
                        },
                        new
                        {
                            Id = 6,
                            Description = "A bold coffee infused with dark chocolate and fruity raspberry accents for a unique twist.",
                            Image = "https://coffeehubimg02.blob.core.windows.net/product-images/ChocRaspberryCoffee.png",
                            Name = "Chocolate Raspberry",
                            Price = 8.29m
                        },
                        new
                        {
                            Id = 7,
                            Description = "A refreshing coffee blend with tangy raw mango notes for an unexpected, vibrant flavor.",
                            Image = "https://coffeehubimg02.blob.core.windows.net/product-images/MangoCoffee.png",
                            Name = "Raw Mango",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Light coffee with tropical pineapple hints, delivering a bright and refreshing taste.",
                            Image = "https://coffeehubimg02.blob.core.windows.net/product-images/PineappleCoffee.png",
                            Name = "Pineapple Delight",
                            Price = 7.79m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Smooth coffee infused with roasted pistachio flavor for a creamy, nut-forward finish.",
                            Image = "https://coffeehubimg02.blob.core.windows.net/product-images/PistachioCoffee.png",
                            Name = "Royal Pistachio",
                            Price = 8.49m
                        });
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.Order", b =>
                {
                    b.HasOne("CoffeeHub.Api.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.OrderItem", b =>
                {
                    b.HasOne("CoffeeHub.Api.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHub.Api.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoffeeHub.Api.Models.Product", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.Payment", b =>
                {
                    b.HasOne("CoffeeHub.Api.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("CoffeeHub.Api.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
